version: "3.0"

services:
  # Setup React Container
  client:
    build: ./client
    container_name: congrant_react_app
    expose:
      - ${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/:/app/client/
      - /app/client/node_modules
      - ./client/.env:/app/client/.env
    env_file:
      - ./client/.env
    command: npm run start:dev

networks:
    default:
        external:
            name: ${D_SERVICES_NETWORK}

