ArticleEditor.lang['ja'] = {
    "accessibility": {
        "help-label": "リッチテキストエディタ"
    },
    "editor": {
        "title": "ページ内容",
        "multiple": "複数",
    },
    "placeholders": {
        "figcaption": "キャプションを入力できます",
        "text": "テキストを入力してください",
        "code": "コードを追加してください",
        "layer": "新しいテキストを入力するにはEnterを押してください"
    },
    "popup": {
        "link": "リンク",
        "add": "追加",
        "grid": "グリッド",
        "back": "もどる",
        "image": "画像",
        "snippets": "スニペット",
        "add-image": "画像を追加"
    },
    "shortcuts": {
        "meta-a": "テキストをすべて選択",
        "meta-shift-a": "すべてのブロックを選択",
        "meta-click": "複数のブロックを選択",
        "meta-z": "取り消し",
        "meta-shift-z": "やり直し",
        "meta-shift-m": "テキストの装飾を削除",
        "meta-b": "太字",
        "meta-i": "イタリック",
        "meta-u": "下線",
        "meta-h": "上付き文字",
        "meta-l": "下付き文字",
        "meta-k": "リンク",
        "meta-alt-0": "本文",
        "meta-alt-1": "見出し",
        "meta-alt-2": "小見出し",
        "meta-alt-3": "Heading 3",
        "meta-alt-4": "Heading 4",
        "meta-alt-5": "Heading 5",
        "meta-alt-6": "Heading 6",
        "meta-shift-7": "番号付きリスト",
        "meta-shift-8": "箇条書きリスト",
        "meta-indent": "インデントを下げる",
        "meta-outdent": "インデントを上げる",
        "meta-shift-backspace": "ブロックを削除",
        "meta-shift-d": "ブロックを複製",
        "meta-shift-up": "ブロックを上に移動",
        "meta-shift-down": "ブロックを下に移動"
    },
    "headings": {
        "h1": "見出し",
        "h2": "小見出し",
        "h3": "Heading 3",
        "h4": "Heading 4",
        "h5": "Heading 5",
        "h6": "Heading 6"
    },
    "inline": {
        "bold": "太字",
        "italic": "イタリック",
        "deleted": "取り消し線"
    },
    "list": {
        "unordered-list": "箇条書きリスト",
        "ordered-list": "番号付きリスト",
        "indent": "インデント（字下げ）",
        "outdent": "アウトデント（字上げ）"
    },
    "link": {
        "link": "リンクを追加",
        "edit-link": "リンクを編集",
        "unlink": "リンクを解除",
        "link-in-new-tab": "新しいタブでリンクを開く",
        "save": "保存",
        "insert": "リンクを挿入",
        "cancel": "キャンセル",
        "text": "テキスト",
        "url": "URL"
    },
    "table": {
        "width": "幅",
        "nowrap": "テキストを折り返さない",
        "save": "保存",
        "cancel": "キャンセル",
        "table-cell": "テーブルセル",
        "add-head": "見出しを追加",
        "remove-head": "見出しを削除",
        "add-row-below": "↓下に行を挿入",
        "add-row-above": "↑上に行を挿入",
        "remove-row": "行を削除",
        "add-column-after": "→右に列を挿入",
        "add-column-before": "←左に列を挿入",
        "remove-column": "列を削除"
    },
    "image": {
        "or": "OR",
        "alt-text": "Altテキスト",
        "save": "保存",
        "link": "リンク",
        "width": "幅",
        "delete": "削除",
        "cancel": "キャンセル",
        "insert": "挿入",
        "caption": "キャプション",
        "link-in-new-tab": "新しいタブでリンクを開く",
        "url-placeholder": "画像のURLをペーストしてください",
        "upload-new-placeholder": "画像をドラッグもしくはクリックして選択"
    },
    "code": {
        "code": "コード",
        "insert": "挿入",
        "save": "保存",
        "cancel": "キャンセル"
    },
    "embed": {
        "embed": "埋め込み",
        "caption": "キャプション",
        "insert": "挿入",
        "save": "保存",
        "cancel": "キャンセル",
        "description": "埋め込みコード/HTMLコードをペーストしてください（Youtube、Vimeoの場合はURLでも可）",
        "responsive-video": "画面の幅に最適化"
    },
    "upload": {
        "placeholder": "ドラッグもしくはクリックして選択"
    },
    "templates": {
        "templates": "テンプレート"
    },
    "snippets": {
        "snippets": "スニペット"
    },
    "form": {
        "link": "リンク",
        "url": "URL",
        "text": "テキスト",
        "name": "名前",
        "alt-text": "Altテキスト",
        "image": "画像",
        "upload": "アップロード",
        "alignment": "整列",
        "outset": "開始位置",
        "valign": "垂直方向の配置"
    },
    "buttons": {
        "mobile-view": "スマホ表示",
        "cancel": "キャンセル",
        "insert": "挿入",
        "unlink": "リンクを解除",
        "save": "保存",
        "add": "追加",
        "transform-to-text": "テキストに変更",
        "align": "整列",
        "valign": "垂直方向の配置",
        "outset": "開始位置",
        "indent": "インデント（字下げ）",
        "outdent": "アウトデント（字上げ）",
        "head": "見出し",
        "row": "行",
        "cell": "セル",
        "html": "HTML",
        "templates": "テンプレート",
        "shortcuts": "ショートカット",
        "format": "フォーマット",
        "bold": "太字",
        "italic": "イタリック",
        "deleted": "取り消し線",
        "underline": "下線",
        "table": "テーブル（表）",
        "link": "リンク",
        "undo": "取り消し",
        "redo": "やり直し",
        "style": "文字スタイル",
        "config": "設定",
        "settings": "設定",
        "text": "テキスト",
        "embed": "埋め込み",
        "grid": "グリッド（分割）",
        "image": "画像",
        "list": "リスト",
        "delete": "削除",
        "duplicate": "複製",
        "sort": "ソート",
        "edit": "編集",
        "inline": "インライン"
    },
    "blocks": {
        "noneditable": "編集不可",
        "paragraph": "本文",
        "heading": "見出し",
        "image": "画像",
        "figcaption": "Figcaption",
        "embed": "埋め込み",
        "line": "ライン（線）",
        "code": "コード",
        "quote": "引用",
        "quoteitem": "段落",
        "snippet": "スニペット",
        "column": "カラム",
        "grid": "グリッド（分割）",
        "list": "リスト",
        "table": "テーブル（表）",
        "layer": "レイヤー",
        "row": "行",
        "text": "テキスト",
        "cell": "セル",
        "dlist": "Definition List", 
        "address": "Address",
        "form": "フォーム",
        "card": "カード"
    }
};